travis:
  secure:
    BINSTAR_TOKEN: LGfmxCUtuUf+SB+8yVJdC8e1psaT94W0zy6/IY2GFmqhzlmQWJLzKTNugvzR86vrmi+vZutGFobi/raM166CNHC4+eYanl/QDGAQr8CdV8Qv8pahOKhVdQXSaCevXvFGLtQCD2C9zAJ08eIvYbKZNfAAFjboWglkfwxrBcNtACVYGFh4DqRmOBzZTnN1XjuFY94PFVkGcVCEl/RU/rLBMu28kp7pOXx4Wf8pawuASM+Vy6JQHfeHW3ladp2OQQrWOjBF0HR7ltkKUHM4GqGCUULfOWqKDmu0TAOVIDcAIcrddtuH7wzJgU2cXYREeeGz+9DGBXby2uN0DxKoZUKI2E3aXioOJeBWBJjiGzd63wfi85UUkgidFeDL9BA5/bnlVeqVkcRA2qF7TXP9MNF00D7v/siYVYEL5sLEYP5+2/5kECkLNED9ehKQEMVaLPwU6HdXx0CbNluT3/xIv4G65/6nqMJWmCRdSw+WrXCatdJDSvbz5TsSA/B5nZR3K1veGksxCBKfp2IbdyCxDemszMbu0aBRQTgsBc7tERvEueaWo61d11zPHQZXXjxdUP/fob9qGoxfu2RvlFBg0H1z+90tk6wh1BU3ILp/6uD9fTHq15pSbxY7gW7iWw6WObv0UG5+rJ1iPxrNcJBFuH+eyDnG4+kkGA9wp++8QG2oVBY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
